name: language-engineering
github: BoKleynen/language-engineering-in-haskell
author: Bo Kleynen
version: 0.1.0
description: |
  This package contains some code snippets I wrote for the language engineering topic of
  the course Capita Selecta Computer Science: Artificial Intelligence [H05N0A] at KU Leuven
  (https://onderwijsaanbod.kuleuven.be/2021/syllabi/e/H05N0AE.htm#activetab=doelstellingen_idp1606608).
tested-with: GHC == 8.10.7, GHC == 9.0.2
dependencies: base >=4.14 && <4.16
internal-libraries:
  geo-server:
    source-dirs: geo-server
    exposed-modules:
      - GeoServerShallow
      - GeoServerDeep
  monads:
    source-dirs: monads
    exposed-modules:
      - Basic
      - Exceptions
      - Output
      - State
    dependencies:
      - mtl >= 2.2 && < 2.3
  arith:
    source-dirs: arith
    exposed-modules:
      - Arith
  miniparsec:
    source-dirs: miniparsec
    dependencies:
      - mtl >= 2.2 && < 2.3
    exposed-modules:
      - Miniparsec
      - Miniparsec2
    other-modules:
      - Expr
      - Lambda
tests:
  geo-server-test:
    source-dirs: tests/geo-server
    main: Test.hs
    other-modules:
      - GeoServerShallowTest
      - GeoServerDeepTest
    dependencies:
      - geo-server
      - tasty >= 1.4 && < 1.5
      - tasty-hedgehog >= 0.1 && < 1.1
      - tasty-hspec >= 1.2 && < 1.3
      - tasty-quickcheck >= 0.10 && < 0.11
      - hedgehog >= 0.5 && < 1.1
      - hspec >= 2.9 && < 2.10
      - QuickCheck >= 2.14 && < 2.15
  arith-test:
    source-dirs: tests/arith
    main: Test.hs
    dependencies:
      - arith
      - QuickCheck >= 2.14 && < 2.15
      - tasty >= 0.11 && < 1.5
      - tasty-hedgehog >= 0.1 && < 1.1
      - tasty-quickcheck >= 0.10 && < 0.11
      - hedgehog >= 0.5 && < 1.1
  quick:
    source-dirs: tests/quick
    main: Test.hs
    dependencies:
      - QuickCheck >= 2.14 && < 2.15
      - tasty >= 0.11 && < 1.5
      - tasty-quickcheck >= 0.10 && < 0.11
