name: language-engineering
github: BoKleynen/language-engineering-in-haskell
author: Bo Kleynen
version: 0.1.0
description: |
  This package contains some code snippets I wrote for the language engineering topic of
  the course Capita Selecta Computer Science: Artificial Intelligence [H05N0A] at KU Leuven
  (https://onderwijsaanbod.kuleuven.be/2021/syllabi/e/H05N0AE.htm#activetab=doelstellingen_idp1606608).
tested-with: GHC == 8.10.7
dependencies: base >=4.14 && <4.16
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-orphans
  - -Wno-unused-do-bind
internal-libraries:
  geo-server:
    source-dirs: geo-server
    exposed-modules:
      - GeoServerShallow
      - GeoServerDeep
      - Parser
      - TH
    dependencies:
      - parsec >= 3.1 && < 3.2
      - template-haskell >= 2.13 && < 2.17
  monads:
    source-dirs: monads
    exposed-modules:
      - Basic
      - Exceptions
      - Output
      - State
    dependencies:
      - mtl >= 2.2 && < 2.3
  arith:
    source-dirs: arith
    exposed-modules:
      - Arith
  miniparsec:
    source-dirs: miniparsec
    exposed-modules:
      - Miniparsec
      - Miniparsec2
    other-modules:
      - Expr
      - Lambda
    dependencies:
      - mtl >= 2.2 && < 2.3
  th:
    source-dirs: th
    exposed-modules:
      - Th
    other-modules:
      - Lib
    dependencies:
      - template-haskell >= 2.13 && < 2.17
  project:
    source-dirs: project
    exposed-modules: []
    other-modules:
      - Migration
    dependencies:
      - mtl >= 2.2 && < 2.3
      - postgresql-simple >= 0.5 && < 0.7
      - direct-sqlite >= 2.3 && < 2.4
      - text >=1.2 && <1.3
      - text-show >=3.0 && <4.0
tests:
  geo-server-test:
    source-dirs: tests/geo-server
    main: Test.hs
    other-modules:
      - GeoServerShallowTest
      - GeoServerDeepTest
      - ParserTest
      - THTest
    dependencies:
      - geo-server
      - tasty >= 1.4 && < 1.5
      - tasty-hedgehog >= 0.1 && < 1.1
      - tasty-hspec >= 1.2 && < 1.3
      - tasty-quickcheck >= 0.10 && < 0.11
      - hedgehog >= 0.5 && < 1.1
      - hspec >= 2.9 && < 2.10
      - QuickCheck >= 2.14 && < 2.15
  arith-test:
    source-dirs: tests/arith
    main: Test.hs
    dependencies:
      - arith
      - QuickCheck >= 2.14 && < 2.15
      - tasty >= 0.11 && < 1.5
      - tasty-hedgehog >= 0.1 && < 1.1
      - tasty-quickcheck >= 0.10 && < 0.11
      - hedgehog >= 0.5 && < 1.1
  quick:
    source-dirs: tests/quick
    main: Test.hs
    dependencies:
      - QuickCheck >= 2.14 && < 2.15
      - tasty >= 0.11 && < 1.5
      - tasty-quickcheck >= 0.10 && < 0.11
  project-test:
    source-dirs: tests/project
    main: Test.hs
    dependencies:
      - project
      - tasty >= 1.4 && < 1.5
      - tasty-hspec >= 1.2 && < 1.3
      - hspec >= 2.9 && < 2.10
