name: language-engineering
version: 0.1.0
description: |
  This package contains some code snippets I wrote for the language engineering topic of
  the course Capita Selecta Computer Science: Artificial Intelligence [H05N0A] at KU Leuven
  (https://onderwijsaanbod.kuleuven.be/2021/syllabi/e/H05N0AE.htm#activetab=doelstellingen_idp1606608).
dependencies: base >=4.14 && <4.15
internal-libraries:
  geo-server:
    source-dirs: geo-server
    exposed-modules:
      - GeoServerShallow
      - GeoServerDeep
    other-modules: []
  monads:
    source-dirs: monads
    exposed-modules:
      - Basic
      - Exceptions
      - Output
      - State
    other-modules: []
tests:
  geo-server-test:
    source-dirs: tests/geo-server
    main: Test.hs
    other-modules:
      - GeoServerShallowTest
      - GeoServerDeepTest
    dependencies:
      - geo-server
      - tasty >= 1.4 && < 1.5
      - tasty-hspec >= 1.2 && < 1.3
      - hspec >= 2.9 && < 2.10
