module Example where

-- migration do
--   table "movies" do
--     integer "id"
--     string "name"
--     integer "duration" do
--       index
--       unique
--       primaryKey
--       nullable
--     index name
--     unique $ index ["id", "name"]
--
--   dropTable "movies"
--
--   alterTable "movies" do
--     renameTo "videos"
--     renameTable "name" "title"
--     changeColumnNull "name" False
--
--   createTable "reviews" do
--     integer "id" primaryKey
--     integer "movie_id" do
--       references "movies" "id"
